### ISSUE TITLE
Missing new parameters (BSA) in "Dimensions and base units"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Documentation#4]
Parameter BSA is missing in the "Dimensions and base units"-section. Perhaps also other new paramers (are there any?), too.

**Comment by Yuri05** [comment]
>Parameter BSA is missing...

I guess you mean missing **Dimensions**?

**Comment by PavelBal** [comment]
OK then, I was confused by seeing a "Dimension" BMI, so I thought... Nevermind :D
